sudo: required
services:
  - docker

before_install:
  - docker build -t dudevo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dudevo/react-test npm test -- --coverage

after_success:
  - docker build -t dudevo/multi-client ./client
  - docker build -t dudevo/multi-nginx ./nginx
  - docker build -t dudevo/multi-server ./server
  - docker build -t dudevo/multi-worker ./worker
  #DOCKER Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker
  - docker push dudevo/multi-client
  - docker push dudevo/multi-nginx
  - docker push dudevo/multi-server
  - docker push dudevo/multi-worker
